eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8751/eureka/
server:
  port: 8759
spring:
  application:
    name: server-zuul
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: server-ribbon
    api-b:
      path: /api-b/**
      serviceId: server-feign